name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      -name: Welcome to Github Actions
       run: echo "my first job"

      -name: Second Steps in github actions
       run: echo "this is second job" 
